library(httr)
library(lubridate)
library(jsonlite)
library(RCurl)
library(urltools)
library(tidyverse)
library(skimr)
library(readxl)
library(data.table)
trafficurl <- URLencode("https://api.inreality.com/v3/data/correlated/presence/csv?api_key=ba3ebeeb-2b80-43f3-a62b-e6aeba28a8ca&startDt=2019-10-01&endDt=2019-11-14&storeId=5d54cfce591c1363c693919e")
newurl <- param_set(trafficurl, key = "endDt", value = Sys.Date()-2)
getdata <- getURL(newurl)
traffic <- read.csv(text = getdata)
shelf <- read_excel("C:/Users/niebankt/Documents/Kefi/Kefi Product Position Table.xlsx", sheet=1)
shelf <- as.data.frame(shelf)
shelf <- setnames(shelf, old=c("Zone_ID"), new =c("SENSOR_CODE"))
shelf$Shelf_Position <- as.factor(shelf$Shelf_Position)
traffic$WDay  <- weekdays(as.Date(traffic$DATE_TIME))
newtraffic <- filter(traffic, WDay != "Sunday", PPC_DWELL_TIME > 0)
newtraffic$Year <- format(as.Date(newtraffic$DATE_TIME,format="%Y-%m-%d"), format = "%Y")
newtraffic$Year <- as.integer(newtraffic$Year)
newtraffic$Month <- month(as.POSIXlt(newtraffic$DATE_TIME, format="%Y-%m-%d"))
newtraffic$Short_Dt <- format(as.Date(newtraffic$DATE_TIME,format="%Y-%m-%d"), format = "%m/%d")
newtraffic$Day <- format(as.Date(newtraffic$DATE_TIME,format="%Y-%m-%d"), format = "%d")
newtraffic$Hour <- format(as.POSIXct(newtraffic$DATE_TIME,format="%Y-%m-%d %H:%M:%S"),"%H")
newtraffic$Awareness_Tm <- ifelse(newtraffic$PPC_DWELL_TIME <= 1, newtraffic$PPC_DWELL_TIME, 0)
newtraffic$Attention_Tm <- ifelse(between(newtraffic$PPC_DWELL_TIME,2,9), newtraffic$PPC_DWELL_TIME, 0)
newtraffic$Engagement_Tm <- ifelse(newtraffic$PPC_DWELL_TIME >= 10, newtraffic$PPC_DWELL_TIME, 0)
newtraffic$Attention_Cnt <- ifelse(newtraffic$Attention_Tm>0,1,0)
newtraffic$Engagement_Cnt <- ifelse(newtraffic$Engagement_Tm>0,1,0)
newtraffic$SENSOR_CODE <- as.character(newtraffic$SENSOR_CODE)
MTDtraffic <- newtraffic
MTDtraffic$ytd <- year(as.POSIXlt(cut(Sys.Date(),"year"), format="%Y-%m-%d"))
MTDtraffic$crntyr <- ifelse(MTDtraffic$Year == MTDtraffic$ytd,1,0)
MTDtraffic$mtd <- month(as.POSIXlt(cut(Sys.Date(),"month"), format="%Y-%m-%d"))
MTDtraffic$curntmth <- ifelse(MTDtraffic$Month == MTDtraffic$mtd,1,0)
engagmnt <- filter(MTDtraffic, Engagement_Tm > 0)
attentn <- filter(MTDtraffic, Attention_Tm > 0)


